### ISSUE TITLE
SCRUM-173-Entity-Setting

### ISSUE THREAD

**Issue by ranunclulus** [CheeUp/CheeUp-BE#3]
## 📝 개요
- DB 설계한 내용을 JPA 활용을 위해 Java Entity로 옮겨 두기

## ✔️ To-Do
- [ ] 연관 관계 설정 (외래키 없는 방식)
- [ ] FetchType이나 Column 세부 제약 조건 추가
- [ ] Table이랑 Column 옮기기
- [ ] 매핑 테이블

## 👀 ETC

